export const EDIT_LAYER_REQUESTED = 'EDIT_LAYER_REQUESTED';
export const EDITED_LAYER_SUCCESSFULLY = 'EDITED_LAYER_SUCCESSFULLY';
export const EDIT_LAYER_FAILED = 'EDIT_LAYER_FAILED';

export const REMOVE_LAYER_REQUESTED = 'REMOVE_LAYER_REQUESTED';
export const REMOVED_LAYER_SUCCESSFULLY = 'REMOVED_LAYER_SUCCESSFULLY';
export const REMOVE_LAYER_FAILED = 'REMOVE_LAYER_FAILED';

export const SWITCH_ACTIVITY_REQUESTED = 'SWITCH_ACTIVITY_REQUESTED';
export const SWITCHED_ACTIVITY_SUCCESSFULLY = 'SWITCHED_ACTIVITY_SUCCESSFULLY';
export const SWITCH_ACTIVITY_FAILED = 'SWITCH_ACTIVITY_FAILED';

export const ADD_LAYER_REQUESTED = 'ADD_LAYER_REQUESTED';
export const ADDED_LAYER_SUCCESSFULLY = 'ADDED_LAYER_SUCCESSFULLY';
export const ADD_LAYER_FAILED = 'ADD_LAYER_FAILED';